version: "3"

networks:
    network:

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - network

    php:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - network
        env_file:
            - .env